# Welcome to the gulpd configuration file.
#
## Controls the parameters for the Raft consensus group that stores metadata
### about the Megamd cluster.
###
[meta]
home = "/var/lib/megam"
bind_address = ":7777"
hostname = "localhost"
dir = "/var/lib/megam/megamd"
riak = "192.168.1.9:8087"
api = "https://api.megam.io/v2"
amqp = "amqp://guest:guest@localhost:5672/"
provider = "chefsolo"
docker_path = "/var/lib/docker/containers/"
[gulpd]
enabled = "true"
cat_id = "AMS1251530034561286144"
[http]
enabled = "true"
