# Welcome to the Megamd configuration file.
#
## Controls the parameters for the Raft consensus group that stores metadata
### about the Megamd cluster.
###
[meta]
home = "/var/lib/megam"
bind_address = ":7777"
hostname = "localhost"
dir = "/var/lib/megam/megamd"
riak = "192.168.1.9:8087"
api = "https://api.megam.io/v2"
amqp = "amqp://guest:guest@localhost:5672/"
[gulpd]
enabled = "true"
assembly_id = "AMS1251530034561286144"
[http]
enabled = "false"